# Generated by Django 4.1.2 on 2022-10-13 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento_emprestimo',
            name='valor_parcela',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da parcela'),
        ),
        migrations.CreateModel(
            name='Extrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField()),
                ('operacao', models.CharField(choices=[('I', 'Entrada'), ('O', 'Saida')], default='I', max_length=1)),
                ('descritivo', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fk_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.conta', verbose_name='Conta')),
            ],
        ),
        migrations.CreateModel(
            name='Contatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorito', to='cadastro.cliente')),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titular', to='cadastro.cliente')),
            ],
        ),
    ]
